#!/usr/bin/env bash

__ScriptVersion="1.0.0"


#-----------------------------------------------------------------------
#  Check the operation system
#-----------------------------------------------------------------------

OS=$(uname -m)

if [[ !( $OS == "aarch64" || $OS == "arm" || $OS == "i686" || $OS == "x86_84" ) ]];then
echo -e "\e[41m OS Error \e[0m\nYour operation system should be Android."
exit 1
fi

#===  FUNCTION  ================================================================
#         NAME:  usage
#  DESCRIPTION:  Display usage information.
#===============================================================================

function usage ()
{
    cat <<- EOT

  Usage :  meow [options] <arguments>
  
  🐈🐾 - meow is a friendly package manager ✨

  Options:
  
  -h|help                 Display this message
  -v|version              Display script version
  -i|i|install <pkg>      Install the package
  -u|uninstall <pkg>      Uninstall the package
  -f|files <pkg>          Show related files of package
  -s|show <pkg>           Show meta data of package
  -u|upgrade              Upgrade all packages
  up|update  <pkg>        Upgrade the package
  il|installed-list       Show all installed list
  
EOT
echo -e "  Example: \e[32mmeow i \e[35m<package-name>\e[0m"
echo 
}    # ----------  end of function usage  ----------



#-----------------------------------------------------------------------
#  Handle command line arguments
#-----------------------------------------------------------------------

if [ $# = 0 ]; then 
	usage
	exit 1
fi

CMD=$1  # Set first argument
shift 1 # Skip first argument

case $CMD in
  -h|he*) usage ;;
  -v|ver*)
  echo -e "🐈🐾 - meow version\e[32m v$__ScriptVersion\e[0m" ;;
  -i|i*)  apt install "$@" ;;
  -u|un*) apt remove "$@";;
  -f|fil*) dpkg -L "$@" ;;
  -s|sh*) apt show "$@";;
  -u|up*) apt update ;;
  up|upd*) apt full-upgrade "$@";;
  il|installed-l*) apt list --installed "$@";;
  *)
  echo -e "\e[41m Unknown Command Error \e[0m\n'$CMD' Command Not Found. \n(run \e[32m'meow -h'\e[0m for usage information.)\e[0m"; exit 1;;
esac

