#!/usr/bin/env bash

trap 'stop' 2

__ScriptVersion="1.1.0"

#-----------------------------------------------------------------------
#  Check the operation system
#-----------------------------------------------------------------------
OS=$(uname -m)

if [[ !( $OS == "aarch64" || $OS == "arm" || $OS == "i686" || $OS == "x86_84" ) ]];then
echo -e "\e[41m OS Error \e[0m\nYour operation system should be Android."
exit 1
fi


#===  FUNCTION  ================================================================
#         NAME:  usage
#  DESCRIPTION:  Display usage information.
#===============================================================================
function usage ()
{
        cat <<- EOT

  Usage :  lamp [options] 

 🐘👀 - lamp is a web servers manager ✨

  Options: 
  
  -h|help       Display this message
  -v|version    Display script version
  
   start      Start all servers
   stop       Stop all servers
   restart    Restart all servers
   
   ekill      Kill all this application if servers are crashed
  
EOT
echo -e "  Example: \e[32mlamp start \e[0m"
echo
}    # ----------  end of function usage  ----------


#===  FUNCTION  ================================================================
#         NAME:  checkStandardServers
#  DESCRIPTION:  Standard Servers Checker
#  Standard Servers => Apache,PHP,MariaDB
#===============================================================================

function checkStandardServers(){
    
    apacheServer=$(which apachectl)
    phpServer=$(which php)
    mysqlServer=$(which mysql)
    
    if [[ ( !($apacheServer) || !($phpServer) || !($mysqlServer) ) ]]; then
        echo -e  "\e[41m 404 : Standard Servers Not Found \e[0m"
        echo -e "run\e[32m lamp install-deps\e[0m to install standard dependencies."
        exit 1
    fi
}

function startAllServers(){
    echo -e "Servers is running at\e[35m localhost:8080 \e[0m"
    echo -e "\e[41m CTRL + C \e[0m to stop servers. "
    
    # Start Standard Servers
    # sh $PREFIX/etc/init.d/mysql start

    apachectl start
    mysqld > /dev/null 2>&1 & sleep 2
  
    while [[ true ]]; do
    sleep 1
    done
}

# Stop via user interaction
function stop(){
    apachectl stop >> /dev/null 2>&1 
    killall -9 mysqld >> /dev/null 2>&1 
    echo -e "\e[31m Servers have been stopped. \e[0m"
    exit 1
}

function emergencyKill(){
     # Emergency kill
     echo -e "\e[41m Application have been successfully killed. \e[0m"
     
     kill $(ps aux | grep '[m|p|a]' | awk '{print $2}') >> /dev/null 2>&1 & exit 1
}

function checkConnection(){
    if  curl \
        --head \
        --connect-timeout 5 \
        --fail \
        "localhost:8080" > /dev/null 2>&1; then
        echo "good"
    else
    echo -e "\e[41m Connection Error \e[0m"
    echo "Check your internet connection and try again."
    exit 1
    fi
}

function restartServers(){
    if [[ !$( apachectl restart ) ]]; then
    
        apachectl restart
        echo -e "\e[41m Servers Are Restarted \e[0m"

        exit 1
    fi
}

function installDeps(){
    echo installed
}



#-----------------------------------------------------------------------
#  Handle command line arguments
#-----------------------------------------------------------------------

if [[ $# = 0 ]]; then
    usage
    exit 1
fi

CMD=$1
shift 1

  case $CMD in

    -h|hel*     )  usage; exit 0   ;;

    -v|ver*     )  echo -e "🐘👀 - lamp version\e[32m v$__ScriptVersion\e[0m" ; exit 0   ;;
       
       sta*     ) 
    checkStandardServers
    startAllServers
    ;;
    
       sto*     )
       stop
       ;;
       
       rest*)
       restartServers
       ;;
       
        ekill   )
        # kill if application is crashed
    emergencyKill
    ;;
    
        inst*)
        checkConnection
        installDeps
    ;;
     *          )  echo -e "\e[41m 404 \e[0m"
                   echo "Command Not Found"
                   echo -e "(run \e[35m\`lamp -h\`\e[0m for usage information.)"
                   exit 1  ;;

  esac    # --- end of case ---
  